### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by lap1sid** [SereneTeam/alterlinux#11]
一部分をパッケージ化したほうがいいと思います。

- [x] alterlinux-keyring
- [x] alterlinux-wallpaper
- [x] alterlinux-xfce-conf

パッケージングは担当します。

**Comment by Hayao0819** [comment]
いずれそうする予定ですがまだエディションなどがはっきりしていないため延期しています

**Comment by Hayao0819** [comment]
- [ ] alterlinux-wallpaper
- [ ] alterlinux-xfce-conf
- [x] alterlinux-keyring
- [] alterlinux-fcitx-conf
