### ISSUE TITLE
お気に入りアプリのブラウザが選択されていない

### ISSUE THREAD

**Issue by Namaomo** [SereneTeam/alterlinux#12]
xfceのお気に入りのwebブラウザの部分に、何も選択されていなかった。

**Comment by Namaomo** [comment]
alterlinux-2020.02.27-x86_64.isoで発生していました。

**Comment by Hayao0819** [comment]
報告ありがとうございます

**Comment by Hayao0819** [comment]
GUI上では修正できませんでしたが、`exo`から実行すると正常にChromiumがデフォルトに設定されているようになりました。
