### ISSUE TITLE
dev版、dev-stable版のwizard.shの不具合

### ISSUE THREAD

**Issue by mk-linux419** [SereneTeam/alterlinux#13]
# 不具合の概要
wizard.shを実行したときに構文エラーが発生し、実行することができない。
dev版、dev-stable版において確認。他のブランチでも同様の不具合があるかもしれません。
# 修正案
https://github.com/SereneTeam/alterlinux/blob/8bd887dde5e42bd248bd621e1182fb5b5c04e9f2/wizard.sh#L210
の後ろに;;をつける。

**Comment by Hayao0819** [comment]
修正しました！
