### ISSUE TITLE
ブルートゥースが正常に使えない問題

### ISSUE THREAD

**Issue by naoko1010hh** [SereneTeam/alterlinux#23]
2020/03/25 dev版にてbluetoothがサービス起動されていないため、bluetoothを使用することができない。

動作検証環境
実機環境
東芝ダイナブックPT75TBP-BWA
CPU i7-5500U CPU @ 2.40GHz
RAM 8GB
ROM HDD 
![スクリーンショット_2020-03-27_00-37-41](https://user-images.githubusercontent.com/50263013/77665660-5135af00-6fc3-11ea-8c89-4de4198a3cc5.png)
![スクリーンショット_2020-03-26_18-38-44](https://user-images.githubusercontent.com/50263013/77665729-67436f80-6fc3-11ea-9baf-facc2920354f.png)

**Comment by Hayao0819** [comment]
起動時に認証が必要になってしまう

**Comment by Hayao0819** [comment]
認証の無効化+完全な自動起動を実装した
