### ISSUE TITLE
標準ソフトウェアのcpu-xがライブラリ不足で起動しない

### ISSUE THREAD

**Issue by naoko1010hh** [SereneTeam/alterlinux#25]
2020/03/25あるいは2020/03/26ビルドのdev版にてcpu-xが起動しないためターミナルにてcpu-xコマンドを実行したところ、libprocps.so.7ライブラリが不足している模様

動作検証環境 実機
環境
東芝ダイナブックPT75TBP-BWA
CPU i7-5500U CPU @ 2.40GHz
RAM 8GB
ROM HDD
![スクリーンショット_2020-03-28_16-01-04](https://user-images.githubusercontent.com/50263013/77817325-6159a580-710d-11ea-85f1-9ec05b409987.png)

**Comment by Hayao0819** [comment]
3月27日の段階で既に修正済みです
