### ISSUE TITLE
ネットワーク接続ができない

### ISSUE THREAD

**Issue by cymq** [SereneTeam/alterlinux#3]
20200222のNon-Newinstaller版でsystemdのNetworkManager.serviceがdisabledになっているため、ネットワーク接続ができません。

**Comment by Hayao0819** [comment]
報告ありがとうございます。

**Comment by protonesso** [comment]
systemctl enable NetworkManager
systemctl start NetworkManager

**Comment by Hayao0819** [comment]
Calamaresで自動化できてないらしい…？

**Comment by protonesso** [comment]
できる

**Comment by lap1sid** [comment]
https://github.com/SereneTeam/alterlinux-calamares/blob/5c7921ca0d8cd89d9b5a134aac022adbc1f3746b/src/modules/services-systemd/services-systemd.conf#L76

該当部分`false`になっていたので、修正します。

**Comment by lap1sid** [comment]
最新版で修正しました。

**Comment by Hayao0819** [comment]
それは該当部分ではありません。
正常に起動できたかどうかを確認するかというオプションだったはずです。

**Comment by lap1sid** [comment]
違っていたようなので、調査します。

**Comment by Hayao0819** [comment]
修正しました
