### ISSUE TITLE
Broken fonts in Beta7 Installer

### ISSUE THREAD

**Issue by ttepatti** [SereneTeam/alterlinux#4]
**Describe the bug**
In the Serene Linux Beta7 installer, a number of Unicode fonts do not display correctly. I've attached a screenshot below for clarification.

**To Reproduce**
1. Run the Serene Linux Beta7 ISO
2. Select the option to Install
3. The language selection list will open and you can see the broken languages

**Expected behavior**
The languages should display correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/7002801/75125416-07377180-5683-11ea-8357-0c5c3ea4d103.png)

**Comment by lap1sid** [comment]
**Here is AlterLinux.**
But we don't have serenelinux base github...

**Comment by ttepatti** [comment]
> **Here is AlterLinux.**
> But we don't have serenelinux base github...

Ahhh embarrassing, I'm sorry!

**Comment by lap1sid** [comment]
> > **Here is AlterLinux.**
> > But we don't have serenelinux base github...
> 
> Ahhh embarrassing, I'm sorry!

I made it.
https://github.com/SereneTeam/serenelinux-docs/issues
